#Stage 1
FROM node:lts-alpine AS builder
# Add a work directory
WORKDIR /app
# ENV NODE_ENV=production
# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn
# RUN yarn install --production
# Copy app files
COPY . .
# Build the app
# RUN yarn global add typescript @types/node @craco/craco @craco/types
# RUN yarn add -D @craco/types craco-alias @types/yup craco-sass-resources-loader react-app-alias sass @types/recharts
RUN yarn build
# RUN ["node", "craco", "build"]
# CMD ["/bin/bash", "-c", "yarn build"]

#Stage 2
# Bundle static assets with nginx
FROM nginx:1.24.0-alpine-slim AS production
# ENV NODE_ENV=production
# Copy built assets from builder
COPY --from=builder /app/build /usr/share/nginx/html
# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Expose port
EXPOSE 80
# Start nginx
CMD ["nginx", "-g", "daemon off;"]

